name: primer16

on: ['workflow_dispatch']

jobs:
  initialize-firmware:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false 
      max-parallel: 1  
      matrix:
        keyboard: ['primer16']
        keymap: ['default']
        keyboard_config: ['single']
        hardware_config: ['primer16']
        compile_with: ['nice_nano']

    steps:
      - name: Checkout builder repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Update from last run
        run: git pull

      - name: Setup conditions
        id: job_conditions
        run: |
          if [ -d ${{ matrix.keyboard }}-${{ matrix.keymap }}-${{ matrix.keyboard_config }}-${{ matrix.compile_with }} ]; then
            echo "firmware-here=true" >> $GITHUB_ENV
          else
            echo "firmware-here=false" >> $GITHUB_ENV
          fi

      - name: Clone BlueMicro_BLE repository
        if: ${{ env.firmware-here == 'false' }}
        run: git clone https://github.com/jpconstantineau/BlueMicro_BLE.git

      - name: Setup job variables
        id: job_variables
        run: |
          firmware_name="${{ matrix.keyboard }}-${{ matrix.keymap }}-${{ matrix.keyboard_config }}-${{ matrix.compile_with }}"
          hardware_config_path=$(find ${{ matrix.keyboard }}/hardware/ -name hardware_config.h | grep ${{ matrix.hardware_config }})
          echo "firmware-name=$firmware_name" >> $GITHUB_ENV
          echo "hardware-config=$hardware_config_path" >> $GITHUB_ENV

      - name: Create firmware folder
        if: ${{ env.firmware-here == 'false' }}
        run: mkdir ${{ env.firmware-name }}

      - name: Copy main firmware files
        if: ${{ env.firmware-here == 'false' }}
        run: |
          cp BlueMicro_BLE/firmware/*.cpp ${{ env.firmware-name }}
          cp BlueMicro_BLE/firmware/*.h ${{ env.firmware-name }}
          cp BlueMicro_BLE/firmware/firmware.ino ${{ env.firmware-name }}/${{ env.firmware-name }}.ino

      - name: Copy board specific files
        if: ${{ env.firmware-here == 'false' }}
        run: |
          cp ${{ matrix.keyboard }}/config/${{ matrix.keyboard_config }}/keyboard_config.h ${{ env.firmware-name }}
          cp ${{ env.hardware-config }} ${{ env.firmware-name }}
          cp ${{ matrix.keyboard }}/keymaps/${{ matrix.keymap }}/keymap.h ${{ env.firmware-name }}
          cp ${{ matrix.keyboard }}/keymaps/${{ matrix.keymap }}/keymap.cpp ${{ env.firmware-name }}

      - name: Remove BlueMicro_BLE repository
        if: ${{ env.firmware-here == 'false' }}
        run: rm -r BlueMicro_BLE

      - name: Check back in the changes to this repo
        if: ${{ env.firmware-here == 'false' }}
        run: |
          ls -l
          git config --global user.name 'gh-actions'
          git config --global user.email 'gh-actions@noreply.github.com'
          git add ${{ env.firmware-name }}
          git commit -m "Initialized ${{ env.firmware-name }} using GitHub Actions"
          git push

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1

      - name: Install BSP and Libraries
        env:
          BSP_URL: https://github.com/jpconstantineau/Community_nRF52_Arduino/releases/latest/download/package_jpconstantineau_boards_index.json
          BSP_PATH: .arduino15/packages/community_nrf52/hardware/nrf52
          BSP_URL_ADA: https://adafruit.github.io/arduino-board-index/package_adafruit_index.json
          BSP_PATH_ADA: .arduino15/packages/adafruit/hardware/nrf52
        run: |
          pip3 install adafruit-nrfutil
          arduino-cli config init
          arduino-cli core update-index
          arduino-cli core update-index --additional-urls $BSP_URL_ADA
          arduino-cli core install adafruit:nrf52 --additional-urls $BSP_URL_ADA
          arduino-cli core update-index --additional-urls $BSP_URL
          arduino-cli core install community_nrf52:nrf52 --additional-urls $BSP_URL
          arduino-cli core list
          arduino-cli board listall
          arduino-cli lib list

      - name: Compile Firmware
        env:
          BSP_PATH: .arduino15/packages/adafruit/hardware/nrf52
        run: |
          arduino-cli compile --fqbn community_nrf52:nrf52:${{ matrix.compile_with }} ./${{ env.firmware-name }} --output-dir ./${{ env.firmware-name }}/build

      - name: Create UF2 for nRF52840 boards
        if: ${{ (matrix.compile_with != 'feather_nrf52832') && (matrix.compile_with != '4x4macropad_nrf52832') && (matrix.compile_with != 'bluemicro2_1') }}
        env:
          BSP_PATH: .arduino15/packages/adafruit/hardware/nrf52
        run: |
          BSP_VERSION=`eval ls $HOME/$BSP_PATH`
          python $HOME/$BSP_PATH/$BSP_VERSION/tools/uf2conv/uf2conv.py ./${{ env.firmware-name }}/build/${{ env.firmware-name }}.ino.hex -c -f 0xADA52840 -o ./${{ env.firmware-name }}/build/${{ env.firmware-name }}.ino.uf2

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.firmware-name }}
          path: |
            ${{ env.firmware-name }}/build
